### ISSUE TITLE
Will my NodeMCU update itself or does I need to flash the new .bin?

### ISSUE THREAD

**Issue by MagTun** [opendata-stuttgart/meta#100]
I have seen on this link https://www.madavi.de/sensor/update/data/ that the `.bin` file is sometimes updated. 
Do I have to update my NodeMCU by flashing the new `.bin` (in that case, is my configuration saved?) or is the update done automatically via OTA?

**Comment by ricki-z** [comment]
If you haven't changed the configuration the sensor should update automatically via OTA.
In the case that you have deactivated the auto update you can flash a new firmware version without losing the configuration. The configuration ist saved in another part of the flash memory.

**Comment by MagTun** [comment]
Awesome work!
