### ISSUE TITLE
Archivdaten vom 21.11.2018 fehlen

### ISSUE THREAD

**Issue by shred** [opendata-stuttgart/meta#106]
Siehe: https://archive.luftdaten.info/2018-11-21/

Leider fehlen die Daten für den Tag auch im `csv_per_month`-Ordner.

**Comment by shred** [comment]
Gibt es Neuigkeiten hierzu? Sind die Daten noch restaurierbar?

**Comment by Bouni** [comment]
Es scheint das am 16. August irendwas kaput gegangen ist, seit diesem Tag gibts nichts neues mehr unter archive.luftdaten.info

**Comment by ricki-z** [comment]
Die Daten ab dem 16. August sollten in den nächsten Tagen nachkommen und dann auch wieder aktuell gehalten werden.
Es gab ein kleines Performanceproblem auf dem betreffenden Server, so daß die Archivierung temporär ausgesetzt wurde. Naja, und das ganze natürlich während der Urlaubszeit ...

**Comment by shred** [comment]
Wann auch sonst? :wink:

@ricki-z Weißt du auch etwas zu den Daten vom 21.11.2018? Dann können wir den Bug schließen.

**Comment by ricki-z** [comment]
Die Daten selbst liegen noch als Datenbank-Backup auf einem der Server. Das Zurückspielen und als Archiv speichern ist aber nicht wirklich einfach (Koordinaten, die sich inzwischen geändert haben).
Wenn also ein fehlender Tag kein größeres Problem ist, würde ich das gern lassen.

**Comment by shred** [comment]
Es wäre die einzige Lücke in meiner eigenen Datenbank für meinen Sensor. Aber eigentlich ist es nur ein Schönheitsfehler, kein echtes Problem. Dafür lohnt sich ein größerer Aufwand nicht.

Da sich hier sonst niemand deshalb gemeldet hat, schließe ich den Bug von meiner Seite.
