### ISSUE TITLE
Configure GY-BM EP280 sensor

### ISSUE THREAD

**Issue by polvonbraun** [opendata-stuttgart/meta#107]
Hallo,

Mein ester Sensor ist schon seid einiger Zeit online, nun wollte ich noch einen zweiten zusammen bauen und an einer Anderen Lokalität aufbauen.

Für den ersten Sensor verwende ich zusätzlich einen DHT22 Chip.
Für meinen Zweiten habe ich mir nun einen GY-BM EP280 Chip gekauft.

Ich habe jetzt alles zusammengebaut und die Firmeware geflashed. Es scheint soweit auch zu klappen, der Sensor liefert Daten zum Feinstaub: https://www.madavi.de/sensor/graph.php?sensor=esp8266-9001232-sds011
Es tauchen allerdings keine Werte zum BME280 auf...

Hier in der [Anleitung ](https://luftdaten.info/faq/#toggle-id-14) steht: "Nach den Anschließen müssen die Sensoren noch in der Konfiguration aktiviert werden." Allerdings habe ich keine Ahnung was das genau bedeuten soll... Wenn ich mich zum konfigurieren mit dem NodeMCU verbinde finde ich dort nichts zum "konfigurieren" außer WiFi.

Hoffe jemand kann mir weiterhelfen, ich habe mich an die Infos in dieser [Anleitung ](https://luftdaten.info/faq/#toggle-id-14) gehalten.
Vielleicht habe ich etwas bezüglich I2C falsch gemacht, damit kenne ich mich nicht wirklich aus... 
GND des BME280  habe ich an den gleichen wie sds011 angeschlossen.

Hier ein Paar Bilder wie das ganze im Moment bei mir aussieht:

![img_20190127_141825_802](https://user-images.githubusercontent.com/47081643/51801974-2af07400-2245-11e9-90ef-e250d0a29b3c.jpg)
![img_20190127_141242_026](https://user-images.githubusercontent.com/47081643/51801976-2d52ce00-2245-11e9-97b1-5b6cfdee6af5.jpg)
![img_20190127_141242_026](https://user-images.githubusercontent.com/47081643/51801979-2fb52800-2245-11e9-921f-5752b20a4925.jpg)
![img_20190127_150728_357_1920x1080](https://user-images.githubusercontent.com/47081643/51801993-5a9f7c00-2245-11e9-9ef3-02f746c84f2f.jpg)

![screencapture-192-168-4-1-config-2019-01-27-14_41_02](https://user-images.githubusercontent.com/47081643/51801912-41e29680-2244-11e9-8dfa-eb9c08da1cd5.png)
![screencapture-192-168-4-1-config-2019-01-27-14_02_49](https://user-images.githubusercontent.com/47081643/51801913-41e29680-2244-11e9-8586-265a67762059.png)

**Comment by ropeters68** [comment]
A few releases ago a smaller initial logon screen was introduced. In this sceen you should fill in the network credentials and save/restart . To change the sensor settings you will need to logon a second time by entering the IP address of the sensor in your browser (the IP address is generated by your wifi router), then you will get the full configuration page.

**Comment by polvonbraun** [comment]
@ropeters68 thank you very much, this was the decisive tip I needed.

the sensor is working nor and logging data from the BME 280!

![screencapture-192-168-178-65-values-2019-01-27-20_38_45](https://user-images.githubusercontent.com/47081643/51805927-d31d3180-2273-11e9-84ef-7b14ce1a36ab.png)

**Comment by ricki-z** [comment]
@polvonbraun can you close this issue?
