### ISSUE TITLE
BME280 und OLED-Display

### ISSUE THREAD

**Issue by JoachimMeyer** [opendata-stuttgart/meta#109]
Kann mir jemand sagen, ob/wie ich einen Sensor BME280 (I2C) zusammen mit einem OLED-Display (I2C) anschließen kann ? Laut FAQ wird beides an D3/D4 angeschlossen.

Joachim

**Comment by ropeters68** [comment]
Yes, you can connect both, I use a small breadboard to connect BME and OLED to D3/D4.
----Origineel Bericht----
Van : notifications@github.com
Datum : 07/02/2019 14:16
Aan : meta@noreply.github.com
Cc : subscribed@noreply.github.com
Onderwerp : [opendata-stuttgart/meta] BME280 und OLED-Display (#109)
Kann mir jemand sagen, ob/wie ich einen Sensor BME280 (I2C) zusammen mit einem OLED-Display (I2C) anschließen kann ? Laut FAQ wird beides an D3/D4 angeschlossen.
Joachim
