### ISSUE TITLE
API für neuste Messungen nicht verfügbar

### ISSUE THREAD

**Issue by marcelreppi** [opendata-stuttgart/meta#136]
Hallo,
die API mit der folgenden URL scheint nicht mehr erreichbar zu sein: 
http://data.sensor.community/airrohr/v1/filter/box

Gibt es eine neue API URL und eventuell eine kleine Dokumentation dafür?
Wann wird diese Funktion wieder verfügbar sein?

Etwas Hintergrundinformationen: 
Ich benutze die API aktuell um alle IDs von Sensoren zu finden, die sich in einer bestimmten bbox befinden damit ich danach alle CSV Dateien von diesen Sensoren aus dem Archiv herunterladen kann.
Gibt es vielleicht einen eleganteren Weg?

Vielen Dank für die Hilfe und dieses tolle Projekt!

**Comment by ricki-z** [comment]
Hallo,

es gab einen Datenbankcrash und das Wiederherstellen hat etwas länger gedauert. Die Rechenzentren sind gerade alle etwas mehr als üblich ausgelastet.

Zum Datendownload: Wenn man nicht unnötig viele Daten herunterladen will, ist der angegebene Weg der eleganteste. Alternativ könnte man alle 3-4 Minuten die Daten über den bbox-Filter herunterladen und in eine Datenbank kopieren. In den Werten gibt es eine ID für die Messung, über die man dann Dubletten herausfiltern kann. Aber dieses Vorgehen belastet unsere Server natürlich deutlich mehr (immer hochgerechnet auf ein paar mehr Nutzer).

**Comment by marcelreppi** [comment]
Danke für schnelle Antwort!

**Comment by marcelreppi** [comment]
Hallo,
seit ein paar Tagen funktioniert es leider wieder nicht mehr. 
Sind die Server wieder down?

**Comment by marcelreppi** [comment]
Hallo,

der Endpunkt funktioniert wieder nicht. Dieses mal kommt ein 404.

Wird der Endpunkt noch unterstützt? 
Wurde die URL geändert?

Danke und beste Grüße!

**Comment by YaguraStation** [comment]
@marcelreppi Did you see #150 ? Same thing?

**Comment by marcelreppi** [comment]
Yes it's the same issue.

**Comment by YaguraStation** [comment]
Maybe close this rather then and follow #150
