### ISSUE TITLE
Archive server very slow

### ISSUE THREAD

**Issue by marcelreppi** [opendata-stuttgart/meta#141]
Hey,

in recent days the access times and download speed for the archive has been very slow.
It did not used to be like this.
How long will this last?
 
Best regards
Marcel

Edit: Sorry for opening the issue twice by mistake.

**Comment by ricki-z** [comment]
Hello,
we have moved the archive to another server. Can you check this server? It should show a line "User logged in, proceed." in the directory listings (DNS updates may need some time ...).

**Comment by marcelreppi** [comment]
Everything working well! Thanks a lot!

Btw: The old archive URL now redirects to the new website sensor.community.
Congratulations on the new website! It looks great 👏

**Comment by ricki-z** [comment]
We are moving all "old" server names to the new domain sensor.community step by step. Most can be easily redirected. This will be done if the new sites are working as expected (i.e. for the main site we don't have completed all translations).
