### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by mczapala** [opendata-stuttgart/meta#149]
Hello, when trying to use data.sensor.community v1 API, I get certificate error: SSL_ERROR_BAD_CERT_DOMAIN. Certificate says it is issued to domain devices.sensor.community.

**Comment by tommasosansone91** [comment]
I have a similar SSLError:
HTTPSConnectionPool(host='data.sensor.community', port=443): Max retries exceeded with url: /static/v2/data.json (Caused by SSLError(CertificateError("hostname 'data.sensor.community' doesn't match 'devices.sensor.community'",),))

**Comment by ricki-z** [comment]
We had to shutdown the data.sensor.community server for a while. There seems to be some sites (including our map) and tools and apps that are generating too many request in a short time.
The last days I had to split the requests over more servers. At the moment the servers are up again.
