### ISSUE TITLE
where is the API documentation

### ISSUE THREAD

**Issue by derkod** [opendata-stuttgart/meta#155]
In several issues I see references to https://data.sensor.community/airrohr/v1/filter/
but I am unable to find the documentation that describes this API.
Can anybody help me to find it?

**Comment by pjgueno** [comment]
https://github.com/opendata-stuttgart/meta/wiki/EN-APIs

**Comment by derkod** [comment]
Ah, I can read German and saw no need to switch to English. I should have done so. They differ :-(
Thanks!
