### ISSUE TITLE
Dokumentation für Filter

### ISSUE THREAD

**Issue by calipee** [opendata-stuttgart/meta#156]
Hi, 

gibt es eine Dokumentation der API in der sämtliche Filter und weitere Parameter beschrieben werden? 
Ich habe bisher immer nur zufällig in verschiedenen Posts Endpoints gefunden wie z.B. data.sensor.community/airrohr/v1/filter/country=DE&type=Laerm.
Die Dokumentation unter https://github.com/opendata-stuttgart/meta/wiki/APIs bietet ja leider keine Informationen über den Abruf von Daten, sondern nur wie man Daten publishen kann.

Ich hoffe jemand kann mir weiterhelfen, vielen Dank schonmal.

**Comment by pjgueno** [comment]
https://github.com/opendata-stuttgart/meta/wiki/EN-APIs

**Comment by calipee** [comment]
Vielen Dank, hatte das wohl immer wieder überlesen.
