### ISSUE TITLE
Local HTTP-Request to Device possible? How to get a JSON-String back?

### ISSUE THREAD

**Issue by DeepHyperspace** [opendata-stuttgart/meta#164]
I have recently put my dust sensor into operation. I wanted to know if it is possible to send a local HTTP request to the device itself, instead of using the webapi, so that you are independent of an internet connection.

I am a big fan of Node-Red, the following shows what I tried so far. Using the WEB-API I get a nice JSON object back of course. (Screenshot 1)
I tried it with the http://192.168.178.44/values, but there I get the whole HTML code back, I could of course read the values out of it, but maybe there is a URL that returns a JSON string that I could interpret easier. Does this feature exist?

![CloudAPI](https://user-images.githubusercontent.com/3355024/166095658-1c87644f-cf51-440f-8444-9fff1ff05dbf.png)
![LocalAPI](https://user-images.githubusercontent.com/3355024/166095660-7394d15d-e4a9-4491-b850-f2df62f32a33.png)

**Comment by ricki-z** [comment]
To read a JSON directly from the device you need to use the address http://192.168.178.44/data.json
There is also an endpoint for prometheus metrics which is also using JSON format.

**Comment by DeepHyperspace** [comment]
Thanks a lot that was exactly what I was searching for 😊
I was not able to find that informationen, is that documented somewhere?
