### ISSUE TITLE
openair-project.org

### ISSUE THREAD

**Issue by Marwe** [opendata-stuttgart/meta#34]
We should keep an eye on this project and its software:
http://www.openair-project.org/

The openair project is a Natural Environment Research Council (NERC) knowledge exchange project that aims to provide a collection of open-source tools for the analysis of air pollution data. These pages provide some background information to the project. The project is also supported by Defra.

R package: _install.packages('openair')_
Manual: http://www.openair-project.org/PDF/OpenAir_Manual.pdf

Some other data sources are given there:
- _importADMS_ outputs from the ADMS suite of dispersion models (McHugh et al. 1997)
- _importAirbase_ EEA airbase database
- _importAURN_ import hourly data from the UK air quality data archive (http://www.airquality.co.uk/data_and_statistics.php)
- _importKCL_ hourly data from the London Air data archive (http://www.londonair.org.uk/LondonAir/Default.aspx)

and a lot of interesting visualisation options

**Comment by YaguraStation** [comment]
Nice one. I see this project has ended, though. Do you want either put it in the Wiki [1] and/or close the issue? 

[1] https://github.com/opendata-stuttgart/meta/wiki/%C3%A4hnliche-Projekte
