### ISSUE TITLE
OSGEO initiatives (Geocrowdsourcing)

### ISSUE THREAD

**Issue by Marwe** [opendata-stuttgart/meta#35]
OSGEO and its FOSS4G confereceence just launched some initiatives:
- [Geocrowdsourcing CitizenScience FOSS4G](http://wiki.osgeo.org/wiki/Geocrowdsourcing_CitizenScience_FOSS4G)
  -  [geoforall-geocrowd Mailing list](https://lists.osgeo.org/cgi-bin/mailman/listinfo/geoforall-geocrowd), currently no traffic.
- EveryAware - Sensing Air Pollution http://www.everyaware.eu/activities/case-studies/air-quality/
  - [Deliverable 1.1: Report on: sensor selection, calibration and testing; EveryAware platform; smartphone applications](http://www.everyaware.eu/resources/deliverables/D1_1.pdf) "Nitrogen Oxide (NO), Carbon Monoxide (CO) and Nitrogen Dioxide (NO2) are the best fitted gases to measure to detect the presence of traffic pollution. HC and V OC sensors may also have potential."
  - [D1.2 Report on: sensor selection, calibration and testing; EveryAware platform; smartphone applications](http://www.everyaware.eu/resources/deliverables/D1.2.pdf)

**Comment by dokape** [comment]
This issue was opened Nov 2015. 
There was no discussion for at about 2 years.

Can this issue be closed? 
It will not be lost.
