### ISSUE TITLE
current data availability

### ISSUE THREAD

**Issue by Marwe** [opendata-stuttgart/meta#38]
I created a plot of dates and sensors, where you can see the days with measurements:
[plots_sensordata_archive.pdf](https://github.com/opendata-stuttgart/meta/files/124846/plots_sensordata_archive.pdf)

I also put it here:
https://github.com/opendata-stuttgart/meta/blob/master/images/sensordata_avail.pdf

**Comment by dokape** [comment]
Interesting.

Up to now, the numbers of sensor increased enormous.
This chart isn't up to date any more.
Can you close this issue?
