### ISSUE TITLE
HabitatMap, AirCasting und Airbeam

### ISSUE THREAD

**Issue by Marwe** [opendata-stuttgart/meta#40]
Auf  slack.com citizen-science/ gefunden:

an alle, die mit Feinstaubsensoren herumbasteln: HabitatMap hat drei Jahre an der Entwicklung eines Prototypen gearbeitet und teilt alle Informationen zum nachbauen: 
- Project based on Aircasting http://www.takingspace.org/  
- Android App http://aircasting.org/
- Sensor box: https://github.com/vitiral/Airbeam

Fundraising campaign 2014
https://www.kickstarter.com/projects/741031201/airbeam-share-and-improve-your-air

**Comment by YaguraStation** [comment]
@ricki-z hat die genannten Projekte anscheinend Okt 2016 ins Wiki [1] eingepflegt. Bin hier kein Maintainer, aber willste das offene Ticket schließen? 

[1] https://github.com/opendata-stuttgart/meta/wiki/%C3%A4hnliche-Projekte
