### ISSUE TITLE
Feinstaubsensor: Schlauch nötig?

### ISSUE THREAD

**Issue by polygontwist** [opendata-stuttgart/meta#54]
Hallo, auf der Webseite ist ein Schlauch am Sensor, ist der nötig, und wie lang ungefähr?

**Comment by Marwe** [comment]
Ist nicht zwingend notwendig, aber in letzter Zeit bauen wir die ein.

**Comment by taxilof** [comment]
Wozu dient denn der Schlauch?

**Comment by polygontwist** [comment]
ich denke das er damit frische Luft ansaugt und nicht das misst was sich im Gehäuse gesammelt hat.

**Comment by ricki-z** [comment]
Der Schlauch soll dafür sorgen, das möglichst Luft von außerhalb des Rohrs angesaugt wird. Da wir den Sensor nur 15 Sekunden pro Minute einschalten, würde es sonst zu lang dauern, bis wirklich "Frischluft" am Sensor ankommt. Bis dahin würde nur die Luft im Pohr gemessen.
