### ISSUE TITLE
Pfad esptool falsch?

### ISSUE THREAD

**Issue by ElFlosen** [opendata-stuttgart/meta#56]
Habe vor einigen Tagen die Firmeware aufgespielt, allerdings lag bei mir das esptool nicht auf
Windows: %USERPROFILE%\AppData\Local\Arduino15\packages\esp8266\tools\esptool\0.4.**8**
sondern auf
Windows: %USERPROFILE%\AppData\Local\Arduino15\packages\esp8266\tools\esptool\0.4.**9**

Sollte man auf "http://luftdaten.info/feinstaubsensor-bauen/" korrigieren, falls das immer so ist.

Gruß

**Comment by ricki-z** [comment]
Ist korrigiert.
