### ISSUE TITLE
Plastikschlauch

### ISSUE THREAD

**Issue by kratz00** [opendata-stuttgart/meta#63]
Ihr erwaehnt an zwei Stellen einen _20cm Plastikschlauch_ (1, 2).
Ich denke der Schlauch ist als Luftzufuhr fuer den Feinstaubsensor gedacht.
Beim Zusammenbau der Komponenten wird der Schlauch nirgends erwaehnt, auch auf den Bildern ist dieser nirgends zu sehen.

Braucht man den Schlauch oder nicht?

(1) https://github.com/opendata-stuttgart/meta/wiki
(2) https://github.com/opendata-stuttgart/meta/wiki/Bezugsquellen-Einzelteile

**Comment by ricki-z** [comment]
Der Schlauch ist zu empfehlen. Damit wird in den 10 Sekunden "Warmlauf" sicherer Umgebungsluft angesaugt. Ohne Schlauch wird zunächst nur die Luft im Gehäuse angesaugt.
Auf der Seite luftdaten.info ist der Schlauch ganz oben im Bild zu sehen. Ich werde die entsprechende Stelle der Doku aber noch ergänzen.

**Comment by kratz00** [comment]
Danke @ricki-z, ich habe mir heute im Baumarkt 1m Plastikschlauch gekauft (gibt es da nur als Meter-Ware). Auf luftdaten.info habe ich gar nicht geschaut gehabt, sondern nur hier im Wiki. Wie du schon selber festgestellt hast, auch auf luftdaten.info wird der Schlauch beim Zusammenbau der Komponenten nicht erwaehnt.

**Comment by dokape** [comment]
@kratz00 
Sind noch Fragen bzgl. des Schlauchs oder kannst du die Diskussion schließen?

**Comment by kratz00** [comment]
Von mir aus kann die Diskussion geschlossen werden.
Ich hatte sie noch als Erinnerung fuer @ricki-z offen gelassen:

> Ich werde die entsprechende Stelle der Doku aber noch ergänzen.

**Comment by dokape** [comment]
Beschreibung

**Comment by kratz00** [comment]
Super, vielen Dank @dokape !
