### ISSUE TITLE
Messinterval verkürzen

### ISSUE THREAD

**Issue by manne01** [opendata-stuttgart/meta#64]
Guten Abend,
lässt sich denn das Messinterval zwischen den Messläufen auch kürzer einstellen?

Mit freundlichen Grüßen
Euer Manfred

**Comment by ricki-z** [comment]
Theoretisch ja, aber wozu? Die Lebenszeit des Sensors liegt bei 8000 Stunden, also knapp unter 1 Jahr bei Dauerbetrieb.

**Comment by ricki-z** [comment]
Firmware muss dann selbst übersetzt werden, Auto Updates müssen aus sein. Die zu ändernde Variable ist 'sending_intervall_ms'.

**Comment by manne01** [comment]
Vielen Dank für die Tipps, ja, ich denke bei der Lebensdauer macht das keinen Sinn.
