### ISSUE TITLE
Falsche Zeitzone in den Messwerten

### ISSUE THREAD

**Issue by manne01** [opendata-stuttgart/meta#65]
Guten Abend,

wovon hängt denn die Zeitzone ab, die in den Messdaten mitgeliefert wird?
Bei mir ist es aktuell +2 Stunden Unterschied zu den Messwerten.

Kann ich das irgendwo einstellen?

Beste Grüße
Euer Manfred

**Comment by tokudan** [comment]
Bei zwei Stunden Differenz wird vermutlich UTC (https://de.m.wikipedia.org/wiki/Koordinierte_Weltzeit) übermittelt. Damit wird die Zeitzone vermutlich auch nicht auf dem Sensor einstellbar sein, weil der Sensor die ganzen Zeitzonen nicht kennt. Sollte jedes System das deine Zeitzone unterstützt einfach umrechnen können, wenn du mehr Details lieferst kann ich vielleicht mehr sagen.
Notfalls: für Winterzeit eine Stunde dazu rechnen, für Sommerzeit zwei Stunden.

Disclaimer: bin selbst nur Nutzer des Sensors und habe am der Firmware nicht mitgearbeitet.

**Comment by manne01** [comment]
Ich habe nochmal weiter geforscht und muss mich entschuldigen. Die Zeitzone bzw. Uhrzeit ist korrekt. Ich hatte in meinem Auswertungsscript einen fiesen Fehler drin der die Ursache war.

Vielen Dank für die Antwort und nochmals Entschuldigung!

**Comment by ricki-z** [comment]
To answer the question: we are saving time stamps in UTC. Timestamps are saved server side. The NodeMCU doesn't have a real time clock.
