### ISSUE TITLE
Displays

### ISSUE THREAD

**Issue by pathmapper** [opendata-stuttgart/meta#73]
Laut FAQ http://luftdaten.info/faq/#toggle-id-11 können Displays mit dem Treiber-Chip SSD1306 angeschlossen werden.

Dazu folgende Fragen:

- Welche Display sind empfehlenswert? Gibt es neben dem Treiber-Chip SSD1306 weitere Mindestanforderungen (z.B. Anzahl der Pixel)?
- Was wird auf einem angeschlossenen Display standardmäßig angezeigt?
- Gibt es kompatible Displays, die ohne weitere Modifikation für den Außeneinsatz geeignet sind? Falls ja welche?
-  Gibt es eine maximale Kabellänge, damit ein angeschlossenes Display noch funktioniert?

**Comment by dokape** [comment]
Ich habe beim Chineses folgendes Display bestellt

![oled](https://user-images.githubusercontent.com/22255381/30521327-30897e84-9bbe-11e7-8730-87c43a256917.jpg)

**Comment by pathmapper** [comment]
Danke, hilft mir weiter!
Ja, dachte an direkten Außeneinsatz aber Gehäuse für das Display ist auch OK.
