### ISSUE TITLE
BMP280 und DHT22 zeigen jeweils 5 crad zuviel an

### ISSUE THREAD

**Issue by sohnkarlsruhe** [opendata-stuttgart/meta#74]
Hallo, habe mir einen Sensor gebaut aber die Sensoren zeigen ungenaue Werte was die Temperatur angeht an. Luftfeuchtigkeit stimmt einigermaßen. Habe jeweils den BMP und DHT ausprobiert. Was kann ich tun?

**Comment by dokape** [comment]
Hallo,
willkommen beim Feinstaubprojekt :-)
Hier ist die Diskussion zur Dokumentation und Beschreibung des Projektes. 
Fragen zur Software werden hier diskutiert:
https://github.com/opendata-stuttgart/sensors-software/issues

Auch ich habe unterschiedliche Anzeigen bei DHT und in meinem Falle BME.

**Comment by sohnkarlsruhe** [comment]
Der 3. Sensor zeigt jetzt die richtigen Werte an... man muss wohl 10 Stück kaufen und hoffen, dass ein paar funktionieren.
