### ISSUE TITLE
Luftdaten.info auf Github

### ISSUE THREAD

**Issue by sareiizi** [opendata-stuttgart/meta#77]
Archived? Ich wollte ergänzen, dass man sich die Sensor ID aufschreiben sollte. In der Wiki Anleitung steht es auch drin.

**Comment by ricki-z** [comment]
Die Luftdaten.info läuft inzwischen mit Wordpress, und nicht mehr hier bei Github. Deshalb archived.
Den Hinweis habe ich auf Luftdaten.info ergänzt.
