### ISSUE TITLE
luftdaten.info website repo: neue location?

### ISSUE THREAD

**Issue by azrdev** [opendata-stuttgart/meta#82]
https://github.com/opendata-stuttgart/luftdaten.info sagt es sei nur noch ein Archiv, aber sagt nicht wo die website jetzt gehostet wird.
Hintergrund: Auf http://luftdaten.info/feinstaubsensor-bauen/ wird unter "Konfiguration des Feinstaubsensors" verlinkt:
> Sensordaten: http://www.madavi.de/sensor/graph.php
WLAN-Signal: http://www.madavi.de/sensor/signal.php

Das sollten besser https links sein.

**Comment by ricki-z** [comment]
Ich kann nach dem Archivieren des Repo 'luftdaten.info' keine Änderungen mehr daran vornehmen. Deshalb lässt sich dort kein Hinweis mehr eintragen, wie die Seite aktuell gehostet wird.

https-Links haben das Problem, das bei einem Problem mit dem Zertifikat (selbst LetsEncrypt hat manchmal kleinere Probleme) die Links nicht funktionieren. Das ist bei http eher seltener der Fall.

Grundsätzlich funktioniert aber auch ein Aufruf der Seiten via https.
