### ISSUE TITLE
Frage: Gibt es ein Wordpress-Plugin...

### ISSUE THREAD

**Issue by Albager** [opendata-stuttgart/meta#85]
...zur Darstellung der Werte eines oder mehrerer Sensoren auf einer eigenen Wordpress-Seite? (bzw. ist es angedacht, so etwas mal zu machen?)

**Comment by ricki-z** [comment]
Manchmal hilft schon eine Suche in den Wordpress-Plugins ;-) :
https://de.wordpress.org/plugins/live-widget-luftdaten/

**Comment by Albager** [comment]
Hui, cool! Ich hatte eine ganze Weile hier in github gesucht... Bin gar nicht auf die Idee gekommen, bei Wordpress zu gucken. Danke!! 👍
