### ISSUE TITLE
API: How to filter area with negative lat / lon? 

### ISSUE THREAD

**Issue by honkmaster** [opendata-stuttgart/meta#88]
How can is query / filter measurements values from the API with negative longitude or latitude values? If using a URL such as

https://api.luftdaten.info/v1/filter/area=34.226,-2.7213,200 (lat / lon redacted)

the API returns an empty array.

**Comment by ricki-z** [comment]
For the given area: there are no sensors ;-) . The format ist lat,lon,dist , so the coordinated are somewhere in Africa.
But there was also an error in the script. The parameter check refused negative values. This is now changed
The example for Bristol (UK): http://api.luftdaten.info/v1/filter/area=51.45,-2.583333,50

**Comment by honkmaster** [comment]
> For the given area: there are no sensors ;-)

This was as intended (for privacy). I checked, it is working now. Thanks.

**Comment by honkmaster** [comment]
Somehow the API is now dead. 

<img width="682" alt="screen shot 2018-03-30 at 18 52 56" src="https://user-images.githubusercontent.com/1380397/38145957-1e578cd4-344c-11e8-9e73-634ed8d262b3.png">

**Comment by ricki-z** [comment]
The database was defined with a max. ID of 2^31 values. This we have reached now. I'm changing the maximum to 2^63. But this needs some time.
