### ISSUE TITLE
Switch English shopping list links to English AliExpress

### ISSUE THREAD

**Issue by raivisdejus** [opendata-stuttgart/meta#99]
Hi,

Current English How to page is good, but it could be better if the links to shopping list items would lead to English AliExpress as for us non-German speakers it is hard co complete the checkout in Ali express and changing the language the search term is lost.

**Comment by YaguraStation** [comment]
I'm assuming you're talking about the website? In the Wiki I've tried to make it language-independent: https://github.com/opendata-stuttgart/meta/wiki/EN-Components-supply

**Comment by raivisdejus** [comment]
Yes I am talking about the website https://luftdaten.info/en/construction-manual/
This is a small issue, but important one, should be easy to fix.

If necessary I am willing to help with the fix

**Comment by ricki-z** [comment]
Hi @raivisdejus, could you please check the links? I have changed them and the should go now to the english version of AliExpress. The site is setting a language cookie, so you should go to AliExpress directly and switch to english before you test this.

**Comment by raivisdejus** [comment]
@ricki-z Excellent, works like a charm :)
